export const products = [
  {
    id: 1,
    name: "SBR LATEX",
    path: "/img/items/1.jpg",
    notes: "Specialty SBR Latex for Repairs & Waterproofing",
    description: [
      "Provides excellent water impermeability",
      "Offers good workability at reduced water/cement ratio",
      "Excellent bonding between old and new substrate",
      "Acts as a protective coat for steel rebar",
      "Improves flexural, tensile, and bond strength",
      "Enhances waterproofing of concrete/mortar",
      "Improved toughness and flexibility",
      "Allows application in thinner sections",
      "Improves abrasion resistance of flooring",
    ],
    advantages: [
      "Increases flexural, tensile, and bond strength",
      "Improves workability of cementitious mixes at low water-cement ratio",
      "Reduces shrinkage and water permeability",
      "Provides excellent bonding between old and new concrete",
      "Improves adhesion to concrete, stone, bricks, non-oily wood, glass, ceramic tiles",
      "Enhances abrasion resistance",
      "Allows trapped vapors to escape, preventing blistering and adhesion failures",
      "Prevents salt penetration and resists sulphate and chloride attack",
      "Acts as an anti-corrosive for steel rebar",
      "Increases durability of waterproofing coatings even under continuous water contact",
      "Provides resistance to fungal and microbial growth",
      "Allows easy cleaning of tools and equipment used for application",
    ],
    application: [
      "Mix Rexino SBR latex and cement in the ratio of 1.0:1.5 by weight to get a smooth creamy paste.",
      "Apply first coat when the surface is touch-dry and allow it to dry for 4-5 hours.",
      "Apply second coat at right angle to the first coat using the same latex-cement ratio; allow air curing for at least 72 hours.",
      "For horizontal applications, lay a 15-20 mm cement-sand mortar screed (1:3) over the coating to protect the film and allow further work.",
    ],
    packingDetails: ["1 kg Bucket", "5 kg Bucket", "20 kg Bucket"],
    shelfLife: [
      "12 Months",
      "Store between +5°C and 40°C",
      "Keep containers tightly closed when not in use",
      "Protect from freezing and direct sunlight",
    ],
    endImage: ["/img/items/1.jpg", "/img/items/1-1.jpg", "/img/items/1-2.jpg"],
  },
  {
    id: 2,
    name: "SBR Max",
    path: "/img/items/2.jpg",
    notes: "Specialty SBR Max for Repairs & Waterproofing",
    description: [
      "Provides excellent water impermeability",
      "Offers good workability at reduced water/cement ratio",
      "Excellent bonding between old and new substrate",
      "Acts as a protective coat for steel rebar",
      "Useful for improving flexural, tensile, and bond strength and for waterproofing of concrete/mortar",
      "Improved toughness and flexibility",
      "Mixes can be applied in thinner sections",
      "Improves abrasion resistance of flooring",
    ],
    advantages: [
      "Increases flexural, tensile, and bond strength",
      "Improves workability of cementitious mixes at low water-cement ratio",
      "Reduces shrinkage and water permeability",
      "Excellent bonding between old and new concrete",
      "Improves adhesion to most substrates such as concrete, stone, bricks, non-oily wood, glass, ceramic tiles",
      "Improves abrasion resistance",
      "Allows trapped water vapors to escape and prevent blistering and adhesion failures",
      "Prevents salt penetration into the concrete, resisting sulphate and chloride attack",
      "Acts as anti-corrosive for steel rebar",
      "Increases durability of waterproofing coating even in continuous contact with water",
      "Imparts resistance to fungal and microbial growth",
      "Allows easy cleaning of tools and equipment used for application",
    ],
    application: [
      "Mix Rexino SBR Max and cement in the ratio of 1.0:1.5 by weight to get a smooth creamy paste. Apply first coat when the surface is touch-dry and allow it to dry for 4-5 hours.",
      "Apply second coat at right angle to first coat with the same latex-cement ratio; allow the film to air cure for at least 72 hours.",
      "For horizontal application, lay a 15-20 mm cement-sand mortar screed (1:3) over the coating to protect the film and allow further work.",
    ],
    packingDetails: ["20 kg Bucket"],
    shelfLife: [
      "12 Months",
      "Store between +5°C and 40°C",
      "Keep containers tightly closed when not in use",
      "Protect from freezing and direct sunlight",
    ],
    endImage: ["/img/items/2.jpg", "/img/items/2-1.png", "/img/items/2-2.png"],
  },
  {
    id: 3,
    name: "ELASTO L",
    path: "/img/items/3.jpg",
    notes:
      "High Performance and Heavy Duty Reinforced Acrylic Waterproof Coating (500% Elongation)",
    description: [
      "Provides excellent water impermeability",
      "Offers good workability at reduced water/cement ratio",
      "Improved bonding and adhesion to substrates",
      "Improved toughness and flexibility",
      "Mixes can be applied in thinner sections",
      "Raxino Elasto L is a specialty styrene-acrylic latex used as a binder for 2-component cementitious waterproof coating and as an admixture for hydraulic cement mortars",
      "Manufactured using state-of-the-art emulsion polymerization technology ensuring product consistency",
    ],
    areasOfApplication: [
      "Waterproofing of terraces, sunken portions, chajjas, masonry walls, and sloping RCC roofs",
      "External surface coatings",
      "Patch repair mortar for RCC members and floors",
      "Waterproofing mortar and concrete",
    ],
    methodOfApplication: [
      "Remove old treatment completely from slab using mechanical methods and vacuum clean all loose particles and debris",
      "Ensure mother slab is sound and surface prepared; grout internal cracks",
      "Treat surface cracks with Polymer Modified Mortar (PMM)",
      "Saturate slab with water to SSD (saturated surface dry) condition — thoroughly wet but dry to touch, no standing water",
      "Mix Raxino Elasto L and cement in ratio 1:1 by weight. Apply first coat and allow to dry for 4–6 hours",
      "Apply second coat at right angle to the first coat with same ratio, ensuring mechanical key for bonding",
      "Allow film to air cure for at least 72 hours",
      "For horizontal applications, lay a 15–20 mm cement-sand mortar screed (1:3) over coating to protect film and allow further work",
    ],
    precautions: [
      "Always use fresh cement and sharp, clean, well-graded aggregate",
      "Raxino Elasto L is compatible with PPC and OPC cement",
      "Always add cement into latex (not latex into cement)",
      "Do not apply coating over loose or debonded surfaces",
      "Do not use hard water for mixing polymer/cement",
    ],
    packingDetails: ["1 kg Bucket", "5 kg Bucket", "20 kg Bucket"],
    shelfLife: [
      "12 Months",
      "Store between +5°C and 40°C",
      "Keep containers tightly closed when not in use",
      "Protect from freezing and direct sunlight",
    ],
    endImage: ["/img/items/3.jpg", "/img/items/3-1.jpg", "/img/items/3-2.jpg"],
  },
  {
    id: 4,
    name: "ELASTO HS",
    path: "/img/items/4.jpg",
    notes:
      "High Performance and Heavy Duty Reinforced Acrylic Waterproof Coating (700% Elongation)",
    description: [
      "Provides excellent water impermeability",
      "Offers good workability at reduced water/cement ratio",
      "Improved bonding and adhesion to substrates",
      "Improved toughness and flexibility",
      "Mixes can be applied in thinner sections",
      "Raxino Elasto HS is a specialty styrene-acrylic latex used as a binder for 2-component cementitious waterproof coating and as an admixture for hydraulic cement mortars",
      "Manufactured using state-of-the-art emulsion polymerization technology ensuring product consistency",
    ],
    areasOfApplication: [
      "Waterproofing of terraces, sunken portions, chajjas, masonry walls, and sloping RCC roofs",
      "External surface coatings",
      "Patch repair mortar for RCC members and floors",
      "Waterproofing mortar and concrete",
    ],
    methodOfApplication: [
      "For waterproofing of existing slab, strip off the old treatment completely. Adopt mechanical methods to prepare the surface and vacuum clean to remove all loose particles and debris",
      "Mother slab must be sound and mechanically surface prepared; grout internal cracks",
      "Treat surface cracks suitably with Polymer Modified Mortar (PMM)",
      "Thoroughly wet the slab with water until it is saturated. Ensure no stagnant or standing water — mop off any excess. Maintain a saturated surface dry (SSD) condition, where the slab is thoroughly wet but dry to touch before further treatment",
      "Mix Raxino Elasto HS and cement in the ratio 1:1 by weight. Apply the first coat and allow it to dry for 4–6 hours",
      "Apply the second coat at right angle to the first coat using the same latex-cement ratio. Create a suitable mechanical key for better bonding",
      "Allow the film to air cure for at least 72 hours",
      "For horizontal applications, lay a 15–20 mm cement-sand mortar screed (1:3) over the coating to protect the film from damage and allow further work",
    ],
    precautions: [
      "Always use fresh cement and sharp, clean, well-graded aggregate",
      "Raxino Elasto HS is compatible with PPC and OPC cement",
      "Always add cement into latex (not latex into cement)",
      "Do not apply coating over loose or debonded surfaces",
      "Do not use hard water for mixing polymer/cement",
    ],
    packingDetails: ["20 kg Bucket"],
    shelfLife: [
      "12 Months",
      "Store between +5°C and 40°C",
      "Keep containers tightly closed when not in use",
      "Protect from freezing and direct sunlight",
    ],
    endImage: ["/img/items/4.jpg", "/img/items/4-1.jpg", "/img/items/4-2.jpg"],
  },
  {
    id: 5,
    name: "PU BLACK",
    path: "/img/items/5.jpg",
    notes:
      "Water Based Bitumen Modified UV Resistant Elastomeric PU Liquid Membrane (1350% Elongation)",
    description: [
      "Raxino PU Black is a scientific blend of synthetic resins, water-based, cold-applied, single-component elastomeric black PU liquid membrane for protective and waterproof coating",
      "High-performance coating that dries to form an elastic, flexible, impermeable waterproof membrane",
    ],
    advantages: [
      "Recommended for all sloped roofs and non-trafficable roofs",
      "Seamless application with excellent adhesion on concrete",
      "Can be applied on moist surfaces",
      "Excellent elongation and very good low-temperature flexibility",
      "High crack-bridging ability",
      "Excellent water vapor barrier",
    ],
    areasOfApplication: [
      "Protective coating on concrete, brick foundations, and retaining walls",
      "Sandwich membrane in new construction and surface treatment on existing slabs",
      "Waterproofing and protection of structures, concrete, columns, and beams",
      "Podium waterproofing",
      "Refurbishment of APP & Tar felt roofs",
    ],
    methodOfApplication: [
      "After primer coat is completely dried, apply two coats of Raxino PU Black",
      "Apply the second coat only after the first coat is totally cured",
      "For better results, embed glass fiber reinforcement into the first coat of Raxino PU Black while still wet",
      "Raxino PU Black may be diluted up to 15–25% for the first coat to make the material workable and achieve desired coverage",
      "Clean all brushes and tools with water immediately after use",
    ],
    precautions: [
      "Do not mix or use Raxino PU Black with solvents",
      "Protect coating with a proper and appropriate screed",
      "Always keep the substrate moist and SSD (saturated surface dry) before priming",
    ],
    coverage: [
      "Primer Coat: 7–9 m²/kg",
      "Cementitious Surface: 3–4 m²/kg for 2 coats",
    ],
    packingDetails: ["20 kg Bucket"],
    shelfLife: [
      "12 Months in original unopened container from manufacturing date",
    ],
    endImage: ["/img/items/5.jpg", "/img/items/5-1.jpg", "/img/items/5-2.jpg"],
  },
  {
    id: 6,
    name: "PU SEALANT",
    path: "/img/items/6.png",
    notes:
      "High-performance polyurethane sealant for versatile construction applications",
    uses: [
      "Precast elements",
      "Parapets",
      "External walling",
      "Culverts of bridges",
      "Curtain walling and cladding",
      "Retaining walls",
      "Panel walls",
      "Window and door perimeters",
    ],
    packingDetails: ["600 ml Capsule"],
    endImage: ["/img/items/6.png", "/img/items/6-1.jpg", "/img/items/6-2.jpg"],
  },
  {
    id: 7,
    name: "RX-80 EPOXY ADHESIVE",
    path: "/img/items/7.png",
    notes:
      "Standard epoxy resin and hardener adhesive with high bonding strength",
    methodOfApplication: [
      "Roughen, degrease, and dry the surfaces to be bonded",
      "Mix equal volumes of resin and hardener; use the mixture within 45 minutes",
      "Apply a thin layer on both surfaces and clamp the joint overnight",
    ],
    useBy: [
      "Stone",
      "Wood",
      "Metal",
      "Glass",
      "Ceramic",
      "Rubber",
      "Dry concrete",
      "Asbestos",
      "Cement and Bison board",
      "Fabric",
      "Leather",
      "Most rigid plastics",
    ],
    precautions: [
      "Do not swallow",
      "Keep out of the reach of children",
      "In case of an accident, seek doctor’s advice immediately",
      "Avoid contact with eyes and skin",
      "Avoid release to the environment",
      "Wear suitable personal protective equipment during application",
    ],
    packingDetails: ["1.800 kg"],
    endImage: ["/img/items/7.png"],
  },
  {
    id: 8,
    name: "RX-300 TILE ADHESIVE",
    path: "/img/items/8.png",
    notes:
      "Cement-based, polymer-modified tile adhesive for ceramic and semi-vitrified tiles",
    description: [
      "Rexino RX-300 is a cement-based, polymer-modified tile adhesive designed for fixing ceramic and semi-vitrified tiles on floors and walls",
      "Classified as C1TE according to EN 12004 standards, it offers good adhesion strength, reduced vertical slip, and extended open time, making it suitable for professional tiling applications in both residential and commercial projects",
    ],
    standards: ["EN 12004 C1TE"],
    areasOfApplication: [
      "Fixing small and medium-sized tiles on internal floors",
      "Fixing small and medium-sized tiles on internal walls",
    ],
    advantages: [
      "Easy to apply single-component adhesive with extended open time",
      "Superior adhesion properties, adhering well to various substrates",
      "Dual purpose for both floors and walls",
      "Good adhesion and workability suitable for subfloors",
    ],
    storage: ["Store in a cool and dry place", "Protect from direct sunlight"],
    shelfLife: [
      "12 Months from the date of manufacturing in unopened packaging",
    ],
    colour: ["Grey"],
    coverage: ["At 5 mm bed thickness, coverage is 60–70 sq.ft. per 40 kg bag"],
    packingDetails: ["40 kg Bag"],
    endImage: ["/img/items/8.png"],
  },
  {
    id: 9,
    name: "RX-310 TILES ADHESIVE",
    path: "/img/items/9.png",
    notes:
      "Thin-set cementitious dry mix tile adhesive for ceramic, vitrified, and natural stone tiles",
    description: [
      "RX-310 Tile Adhesive is a thin-set cementitious dry mix designed for installing ceramic tiles, vitrified tiles, and natural stones for interior floor and wall applications",
      "Modified tile adhesive, making it ideal for fixing tiles to modern building substrates",
    ],
    standards: ["IS: 15477:2019 TYPE 1", "EN 12004 C1TE"],
    areasOfApplication: [
      "Fixing small and medium-sized tiles on internal floors",
      "Fixing small and medium-sized tiles on internal walls",
    ],
    advantages: [
      "Easy to apply single-component adhesive",
      "Extended open time and superior adhesion properties",
      "Adheres well to various substrates",
      "Dual purpose for both floors and walls",
      "Good adhesion and workability suitable for subfloors",
    ],
    precautions: [
      "For better application, use a notch trowel of appropriate notch size",
    ],
    storage: ["Store in a cool and dry place", "Protect from direct sunlight"],
    shelfLife: [
      "12 Months from the date of manufacturing in unopened packaging",
    ],
    colour: ["Grey"],
    coverage: ["At 8mm bed thickness, coverage is 20–23 sq.ft. per 20 kg bag"],
    packingDetails: ["20 kg Bag"],
    endImage: ["/img/items/9.png"],
  },
  {
    id: 10,
    name: "RX-320 TILES & STONE ADHESIVE",
    path: "/img/items/10.png",
    notes:
      "Cementitious ready-mix, thin-bed polymer-modified adhesive for tiles and stone",
    description: [
      "RX-320 Tile Adhesive is a cementitious ready-mix, thin-bed polymer-modified tile adhesive suitable for interior applications",
      "Its unique properties make it ideal for fixing ceramic tiles, vitrified tiles, natural stones, and granite to most building substrates",
    ],
    standards: ["IS: 15477:2019", "EN 12004 C2TE"],
    areasOfApplication: [
      "Internal floors",
      "Internal walls",
      "Suitable for all types of tiles and stone",
    ],
    advantages: [
      "Easy to apply single-component adhesive",
      "Extended open time with superior adhesion",
      "Dual purpose for both floors and walls",
      "Good adhesion, workability, and high shear bond strength",
      "Provides superior adhesion for porcelain and vitrified tiles",
    ],
    precautions: [
      "For better application, use a notch trowel of appropriate notch size",
    ],
    storage: ["Store in a cool and dry place", "Protect from direct sunlight"],
    shelfLife: [
      "12 Months from the date of manufacturing in unopened condition",
    ],
    colour: ["Grey"],
    coverage: ["At 8mm bed thickness, coverage is 20–23 sq.ft. per 20 kg bag"],
    packingDetails: ["20 kg Bag"],
    endImage: ["/img/items/10.png"],
  },
  {
    id: 11,
    name: "RX-330 STONE ADHESIVE",
    path: "/img/items/11.png",
    notes:
      "Polymer-modified multipurpose thin-set adhesive for stone, mosaic, and tiles",
    description: [
      "RX-330 Stone Adhesive is a polymer-modified, multipurpose thin-set adhesive designed for fixing glass mosaic, brick wall tiles, swimming pool tiles, marble, and natural stones",
      "Suitable for interior and exterior substrates for both wall and floor applications",
    ],
    standards: ["IS: 15477:2019 TYPE 3", "EN 12004 C2TES1"],
    areasOfApplication: [
      "Internal floors",
      "Internal walls",
      "External floors",
      "External walls",
      "Glass mosaic tiles",
      "Brick wall tiles",
      "Swimming pool tiles",
      "Marble and natural stones",
    ],
    advantages: [
      "Multipurpose high-polymer modified thin-set adhesive",
      "Offers high bond strength suitable for various tiles and stones",
      "Suitable for exterior applications",
      "Exhibits high flexibility and non-skid properties",
      "Features water resistance properties",
      "Provides better open time with good workability",
    ],
    storage: ["Store in a cool and dry place", "Protect from direct sunlight"],
    shelfLife: [
      "12 Months from the date of manufacturing in unopened condition",
    ],
    colour: ["White", "Grey"],
    coverage: ["At 8mm bed thickness, coverage is 20–23 sq.ft. per 20 kg bag"],
    packingDetails: ["20 kg Bag"],
    endImage: ["/img/items/11.png"],
  },
  {
    id: 12,
    name: "RX-340 HEAVY STONE ADHESIVE",
    path: "/img/items/12.png",
    notes:
      "Polymer-modified heavy-duty thin-set adhesive for tiles, marble, and natural stones",
    description: [
      "RX-340 Flex Stone Adhesive is a polymer-modified, multipurpose thin-set adhesive",
      "Designed for fixing glass mosaic, brick walls, swimming pool tiles, marble, and natural stones",
      "Suitable for interior and exterior substrates for both wall and floor applications",
    ],
    standards: ["IS: 15477:2019 TYPE 4", "EN 12004 C2TES2"],
    areasOfApplication: [
      "Internal floors",
      "Internal walls",
      "External floors",
      "External walls",
      "Glass mosaic tiles",
      "Brick wall tiles",
      "Swimming pool tiles",
      "Marble and natural stones",
    ],
    advantages: [
      "Multipurpose high-polymer modified thin-set adhesive",
      "Offers high bond strength suitable for exterior application of various tiles and stones",
      "Exhibits high flexibility and non-skid properties",
      "Features water resistance properties",
      "Provides better open time with good workability",
    ],
    storage: ["Store in a cool and dry place", "Protect from direct sunlight"],
    shelfLife: [
      "12 Months from the date of manufacturing in unopened condition",
    ],
    colour: ["White", "Grey"],
    coverage: ["At 8mm bed thickness, coverage is 20–23 sq.ft. per 20 kg bag"],
    packingDetails: ["20 kg Bag"],
    endImage: ["/img/items/12.png"],
  },
  {
    id: 13,
    name: "RX-100 PU ADHESIVE",
    path: "/img/items/13.png",
    notes:
      "High-shear and high-tensile PU-based cladding adhesive for tiles and natural stones.",
    description: [
      "Flexiset is a high-shear and high-tensile improved PU-based cladding adhesive.",
      "Suitable for use on any construction material to affix tiles on various surfaces.",
      "Recommended for a wide range of natural stones such as marble, granite, slate, and all types of tiles.",
    ],
    standards: ["TYPE 5 - Highly Deformable S2", "EN 12004 - R2T"],
    areasOfApplication: [
      "Plywood",
      "Cement sheet",
      "Mild steel (MS)",
      "Stainless steel (SS)",
      "All other surfaces for flooring and walls",
      "Internal and external applications",
      "Domestic, commercial, and industrial settings",
      "Street furniture",
    ],
    howToApply: [
      "Pour Part A and Part B into a clean bucket and mix thoroughly using a mixer machine.",
      "Continue mixing until a homogeneous paste is achieved.",
      "Use an appropriate notched trowel and apply the paste onto the stone/tile with care, ensuring total contact.",
      "Maintain alignment and levelness by pressing the tile/stone left to right and up and down.",
    ],
    advantages: [
      "High flexibility",
      "Strong bonding with no staining",
      "Suitable for application with any tile on any surface",
      "Exhibits water resistance properties",
      "Provides better open time and good workability",
    ],
    storage: ["Store in a cool, dry place", "Protect from direct sunlight"],
    packingDetails: ["Available in 1 kg bucket", "Available in 4 kg bucket"],
    endImage: ["/img/items/13.png"],
  },
];
